### PR TITLE
Redesign

### PR DESCRIPTION
**Pull request by tristen**
[**Demo here**](http://tristen.ca/openaddresses.io/)

This commit covers a bit of stuff but the two main points are:
- Design concept/re-branding
- Light Jekyll build. With the benefit here of sharing a default HTML template. The logic here is kept pretty sparse.

My goal was to create consistent visuals, colors and layout metrics across the frontpage, login, and contribution interface. 
#### Last TODOs
- [x] Merge in latest changes with this branch 
- [x] Double tap on tablet view: There's some small width concerns.
- [x] Map polish. 
  -- Roads could just be more subtle.
  -- Boundaries more defined
  -- Address points with good consistent contrast across zoom levels

cc/ @ingalls

### CODE REVIEW

**Comment by iandees** [comment]
This is pretty darn excellent! Thanks for the refresh, @tristen.

The phrase "Where's the coverage?" feels awkward to me, but I'm not sure what would be better. Maybe "What areas do we cover?".

**Comment by tristen** [comment]
@iandees Agree. I'll try something along the lines of "What areas do we cover?" as you suggest!

**Comment by frewsxcv** [comment]
Lookin great @tristen :cake:

**Comment by kelvinabrokwa** [comment]
That looks great Tristan!

**Pull request merged**
