### PR TITLE
Fix point map

### PR DESCRIPTION
**Pull request by sbma44**
changes mapids for:
- the displayed style on openaddresses.io 
- the dataset that that style points to, so that it matches the dataset to which `machine` uploads each night

image

### CODE REVIEW

**Comment by sbma44** [comment]
cc @geobrando @waldoj @migurski -- would love :eyes: on this so I can be sure I'm not screwing anything up. I think this fixes the map, at least. 

FWIW the text on the buttons looks screwed up because I had made my browser implausibly tiny to take the screenshot

**Comment by iandees** [comment]
Looks good to me. The deleted style stuff is because we're not styling our own version of the basemap?

**Comment by sbma44** [comment]
@iandees honestly I'm unsure of why that stuff got deleted. best guess is that the git version of the style drifted out of sync with the way Studio Classic generates mapnik XML. I don't think it's anything to worry about; these are files generated from the .mss resources, which remain untouched.

**Comment by migurski** [comment]
Awesome!

It seems that our tile layer IDs have not matched, and that’s the issue? Should I instead [change the ID in the dotmap code](https://github.com/openaddresses/machine/blob/03d0c086e202afe1083dcba9acc71c603f6d328d/openaddr/dotmap.py#L151-L152) back to `lp611yvi` instead of changing it here?

**Comment by sbma44** [comment]
@migurski yes, I think that's the root of the issue. What you mention would probably work fine but there's no particular reason to favor one solution over another; I'd say let's just merge this since it's ready to go (and a simpler system to manipulate than `machine`'s internals).

**Comment by sbma44** [comment]
updated OP so the language describing the issue is clearer

**Pull request merged**
