### PR TITLE
remove confusing CC0 language

### PR DESCRIPTION
**Pull request by sbma44**
I think it hurts us more than it helps. Thoughts @ingalls @NelsonMinar @migurski ?

### CODE REVIEW

**Comment by sbma44** [comment]
image

**Comment by iandees** [comment]
Looks good to me.

**Comment by NelsonMinar** [comment]
Looks good. I wonder if we even know enough about all of our sources to say "All data is openly licensed", but that's a vague enough term it doesn't worry me much.

**Comment by migurski** [comment]
+1

**Comment by ingalls** [comment]
:+1:

**Pull request merged**
