### PR TITLE
updated make_mbtiles script

### PR DESCRIPTION
**Pull request by sbma44**
updates download point, fixes vector tile buffering issue, reflects upstream updates to mapbox-upload

cc @migurski

### CODE REVIEW

**Comment by migurski** [comment]
:+1:

**Comment by sbma44** [comment]
fwiw I'm seeing improvement on the buffer issue but there's still some overlap. I think the upstream mb gl js fix is going to be necessary.

**Comment by migurski** [comment]
With the [point map fixed](https://github.com/openaddresses/openaddresses.io/pull/61) and [Dotmap coming from `machine`](https://github.com/openaddresses/machine/blob/master/docs/components.md#dotmap), I’d like to ditch this script. Possible?

**Comment by sbma44** [comment]
sure. might still be useful as a reference to some people but I doubt anyone wants to maintain it -- let's kill it

**Comment by migurski** [comment]
Killed!

**Pull request merged**
