### PR TITLE
switch to GL map

### PR DESCRIPTION
**Pull request by sbma44**
apologies for not realizing this wasn't already done. should be drawing from the correct tileset, but visual confirmation would be lovely

cc @migurski @ingalls 

image

### CODE REVIEW

**Comment by migurski** [comment]
Looks great! Is there a way to configure the Leaflet map to zoom instantaneously, instead of with an animation?

**Comment by migurski** [comment]
Oh also: to turn off the mousewheel scrolljacking?

**Comment by sbma44** [comment]
> Is there a way to configure the Leaflet map to zoom instantaneously, instead of with an animation?

As far as I know the answer to this one is "no", but I'll ask.

> Oh also: to turn off the mousewheel scrolljacking?

definitely possible, but my sense is that this default is pretty normal across the web (certainly it's my own preference). the only content we have below it is the contact link, so I don't think we're inhibiting users from reaching valuable content. can you say more about your thinking on this?

**Comment by migurski** [comment]
In my experience, a full-width map provides no safe zone, so the behavior of the scroll wheel becomes unpredictable. It’s [one of Stamen’s map checklist items](http://content.stamen.com/stamens-checklist-for-maps):

> Mouse scroll should not affect map zoom level when the map is embedded in a page. There's little more irritating than scrolling quickly down a page and getting stuck way zoomed out of a map you hadn't intended to interact with.

**Comment by sbma44** [comment]
hmm, well, I disagree but I've added a commit to disable the behavior

**Comment by migurski** [comment]
Thanks! I’ll merge, it’s so awesome to see this with labels on top.

**Pull request merged**
