### PR TITLE
Point map

### PR DESCRIPTION
**Pull request by sbma44**
[image](https://api.tiles.mapbox.com/v4/sbma44.60b61c3f/page.html?access_token=pk.eyJ1Ijoic2JtYTQ0IiwiYSI6Inh1cm5teEEifQ.LFnEfmyK7mtxU5O64ID4ZA#4/50.85/15.29)

Bash script & style to recreate the point map on openaddresses.io.
- script assumes blank ubuntu AMI & working aws-cli credentials for the data.openaddresses.io bucket
- resulting mbtiles file should be uploaded to mapbox.com
- .tm2 style can then be used in Mapbox Studio with source set appropriately

### CODE REVIEW

**Comment by iandees** [comment]
Nice, thanks @sbma44! I'd love to see this use the pre-concatenated output, but perhaps we're not updating that. @migurski, do you know if machine is mushing everything together yet?

**Comment by sbma44** [comment]
ah, didn't realize there already was a concatenated file. very happy to use that if you can point me toward it.

**Comment by iandees** [comment]
The "Download" link on openaddresses.io links to a zipfile that contains all the processed CSV files. The "pre-concatenated" output I'm talking about was me merging those together to get the initial count. Also, it hasn't been updated in a while.

Bottom line: we don't have what I was talking about, but we should :smile:.

**Comment by migurski** [comment]
I’m not updating it, but that’s a good next step. Is it just a zip file of CSVs, or is it an actual single CSV?

**Comment by ingalls** [comment]
It is currently a zip of CSV's

**Comment by migurski** [comment]
Would it be better to have one big CSV?

**Comment by iandees** [comment]
I've always advertised that our end product is a single giant CSV with all data merged together. Let's maybe add an issue on machine to talk about it there?

**Comment by sbma44** [comment]
Hmm. Can we do both? I think individual CSVs is probably preferable for some use cases. It makes creating regional extracts as simple as a grep one-liners. And ultimately we might want to simplify sources' licensing to something more machine readable (`requires_attribution` for instance), and letting people pick and choose what they're comfortable using.

**Pull request merged**
