### PR TITLE
Search engine

### PR DESCRIPTION
**Pull request by ingalls**

### CODE REVIEW

**Comment by iandees** [comment]
I seem to remember that we explicitly removed the geocoder from the map view because it can be confusing if it doesn't use OpenAddresses data.

Does Mapbox's geocoder consume OA now?

**Comment by iandees** [comment]
...and by "confusing if it doesn't use OA data" I mean that people would see a search box and assume that they're searching across OpenAddresses data.

**Comment by ingalls** [comment]
@iandees Ah gotcha, didn't realize that there was a conversation about this. We do use OpenAddress data heavily but we process it quite a bit and obviously mix it with a bunch of other data sources. My reason for adding it is that I use that map constantly for checking where we have data and where we don't as not all the sources have proper coverage info on them. Being able to quickly zoom to an area of the map makes this process infinitely faster.

**Comment by iandees** [comment]
Yep, makes sense. And I can't really find the previous conversation, so maybe I just made it up.

I think this is OK for now, but it's something to keep in mind the next time we touch up the homepage.

**Comment by ingalls** [comment]
@iandees 👍 I have no problem switching to something else when we do our next redesign

**Pull request merged**
